<?php

/**
 * @file
 * Main functions and hook implementations of the Multisite Review module.
 */

/**
 * The PHP version that should be present in reviewed modules' .info files.
 */
const MULTISITE_REVIEW_PHP_VERSION = '5.2.4';

/**
 * The Features API version that is currently supported.
 */
const MULTISITE_REVIEW_FEATURES_API_VERSION = 'api:1';

/**
 * Implements hook_security_checks().
 */
function multisite_review_security_checks() {
  $checks = array();
  $checks['multisite_review_qa'] = array(
    'title' => t('Multisite QA checks'),
    'callback' => 'multisite_review_qa',
    'success' => t('All Multisite standards are respected'),
    'failure' => t('Some projects do not respect Multisite standards'),
    'module' => 'multisite_review',
    // Specify this file because the callback is here.
    'file' => 'multisite_review',
  );

  return array('multisite_review' => $checks);
}
