<?php

/**
 * @file
 * Main functions and hook implementations of the Multisite Review module.
 */

/**
 * Implements hook_security_checks().
 */
function multisite_review_security_checks() {
  $checks = array();
  $checks['multisite_review_qa'] = array(
    'title' => t('Multisite QA checks'),
    'callback' => 'multisite_review_qa',
    'success' => t('All Multisite standards are respected'),
    'failure' => t('Some projects do not respect Multisite standards'),
    'module' => 'multisite_review',
    // Specify this file because the callback is here.
    'file' => 'multisite_review',
  );

  return array('multisite_review' => $checks);
}
